name: keyboard_visibility_hybrid
description: Flutter plugin for discovering the state of the soft-keyboard visibility on Android and iOS. adapter hybrid.
version: 0.0.1
homepage: https://github.com/allenyulun/flutter_keyboard_visibility

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.github.adee42.keyboardvisibility
    iosPrefix: FLT
    pluginClass: KeyboardVisibilityPlugin
