name: keyboard_visibility
description: Flutter plugin for discovering the state of the soft-keyboard visibility on Android and iOS.
version: 0.5.6
author: adee42 <42adee@gmail.com>
homepage: https://github.com/adee42/flutter_keyboard_visibility/tree/master

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.github.adee42.keyboardvisibility
    iosPrefix: FLT
    pluginClass: KeyboardVisibilityPlugin
